# Demo Configuration for Checkpoint Evaluation
checkpoint_path: "enhanced-qwen3-finetuned/checkpoint-450"
data_path: "data/raw"
max_samples: 20
output_file: "demo_evaluation_report.json"

# Model generation parameters
generation_config:
  max_length: 512
  temperature: 0.7
  do_sample: true
  top_p: 0.9

# Evaluation weights
evaluation_weights:
  knowledge_accuracy: 0.4
  terminology_accuracy: 0.3
  reasoning_quality: 0.3

# Categories to focus on (empty means all)
focus_categories: []